version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/interview/
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Test
          command: trap "go test -v ./..." EXIT
      - run:
          name: Build
          command: go build .
      - run:
          name: Run
          command: ./interview
